name: Update jupyter notebooks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
      - name: pip cache
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: cache-pip-${{ matrix.os }}-${{ matrix.python-version }}

      - name: apt cache
        id: apt-pip
        uses: actions/cache@v3
        with:
          path: /var/cache/apt/archives/
          key: cache-apt-${{ matrix.os }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/checkout@v3
        run: |
          # Install dependencies 
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          sudo apt-get install -y pandoc

          # Build the figures
          make -j4 all

          # Adapt the commit
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add figures
          git commit -m "Build figures"
          git push      
      
      - name: Check doc build
        run: |
          make html
      
       
